# fly.toml app configuration file generated for sunlytics-fly on 2025-07-07T22:13:06+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sunlytics-fly'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
